# Generated by Django 5.1.1 on 2025-02-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportViolations', '0004_remove_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
