# Generated by Django 5.1.1 on 2025-02-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportViolations', '0005_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
        migrations.AlterField(
            model_name='account',
            name='patronymic',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='surname',
            field=models.CharField(max_length=150),
        ),
    ]
